#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RuleSpec {
    pub id: &'static str,
    pub name: &'static str,
    pub category: &'static str,
    pub tlr: &'static str,
    pub lane: &'static str,
    pub docs_url: &'static str,
    pub owner_hint: &'static str,
    pub evidence_kind: &'static str,
    pub severity: &'static str,
    pub repairable: bool,
}

pub const RULES: &[RuleSpec] = &[
    RuleSpec {
        id: "HLT-001-DEAD-MARKER",
        name: "Future-hostile language and placeholder markers",
        category: "vibe",
        tlr: "Entropy",
        lane: "fast",
        docs_url: "docs/audit-rubric.md#future-hostile-language-rule",
        owner_hint: "tools",
        evidence_kind: "repository-scan",
        severity: "high",
        repairable: true,
    },
    RuleSpec {
        id: "HLT-002-GENERATED-MUTATION",
        name: "Generated zone mutation risk",
        category: "generated",
        tlr: "Contracts/data",
        lane: "contract",
        docs_url: "agent/JANKURAI_STANDARD.md#generated-zones",
        owner_hint: "tools",
        evidence_kind: "contract-manifest",
        severity: "high",
        repairable: true,
    },
    RuleSpec {
        id: "HLT-003-OWNERLESS-PATH",
        name: "Ownerless path",
        category: "context",
        tlr: "Context/setup",
        lane: "fast",
        docs_url: "agent/JANKURAI_STANDARD.md#ownership-boundaries",
        owner_hint: "agent",
        evidence_kind: "policy-manifest",
        severity: "high",
        repairable: true,
    },
    RuleSpec {
        id: "HLT-004-UNMAPPED-PROOF",
        name: "Unmapped proof lane",
        category: "proof",
        tlr: "Verification",
        lane: "fast",
        docs_url: "agent/JANKURAI_STANDARD.md#proof-lanes",
        owner_hint: "tools",
        evidence_kind: "policy-manifest",
        severity: "high",
        repairable: true,
    },
    RuleSpec {
        id: "HLT-005-PYTHON-PRODUCT-TRUTH",
        name: "Python product truth spill",
        category: "python",
        tlr: "Business truth",
        lane: "contract",
        docs_url: "docs/agent-native-standard.md",
        owner_hint: "tools",
        evidence_kind: "repository-scan",
        severity: "high",
        repairable: true,
    },
    RuleSpec {
        id: "HLT-006-DIRECT-DB-WRONG-LAYER",
        name: "Direct DB access from wrong layer",
        category: "data",
        tlr: "Contracts/data",
        lane: "db",
        docs_url: "docs/audit-rubric.md#required-shape",
        owner_hint: "tools",
        evidence_kind: "sql",
        severity: "high",
        repairable: true,
    },
    RuleSpec {
        id: "HLT-007-HANDWRITTEN-CONTRACT",
        name: "Handwritten contract drift",
        category: "boundary",
        tlr: "Contracts/data",
        lane: "contract",
        docs_url: "docs/audit-rubric.md#known-vibe-coding-insults",
        owner_hint: "tools",
        evidence_kind: "contract-manifest",
        severity: "high",
        repairable: true,
    },
    RuleSpec {
        id: "HLT-008-FALSE-GREEN-RISK",
        name: "False green test risk",
        category: "test",
        tlr: "Verification",
        lane: "fast",
        docs_url: "docs/testing.md",
        owner_hint: "tools",
        evidence_kind: "test",
        severity: "high",
        repairable: true,
    },
    RuleSpec {
        id: "HLT-009-GENERATED-SECURITY",
        name: "Generated security gap",
        category: "security",
        tlr: "Security, secrets, agency",
        lane: "security",
        docs_url: "docs/audit-rubric.md#top-level-risk-mapping",
        owner_hint: "ops",
        evidence_kind: "workflow-command",
        severity: "high",
        repairable: true,
    },
    RuleSpec {
        id: "HLT-010-SECRET-SPRAWL",
        name: "Secret-like content detected",
        category: "security",
        tlr: "Security, secrets, agency",
        lane: "security",
        docs_url: "docs/audit-rubric.md#top-level-risk-mapping",
        owner_hint: "ops",
        evidence_kind: "repository-scan",
        severity: "critical",
        repairable: true,
    },
    RuleSpec {
        id: "HLT-011-PROMPT-INJECTION",
        name: "Prompt injection risk",
        category: "security",
        tlr: "Security, secrets, agency",
        lane: "security",
        docs_url: "docs/audit-rubric.md#top-level-risk-mapping",
        owner_hint: "ops",
        evidence_kind: "policy-manifest",
        severity: "high",
        repairable: true,
    },
    RuleSpec {
        id: "HLT-012-OVERBROAD-AGENCY",
        name: "Overbroad agent agency",
        category: "security",
        tlr: "Security, secrets, agency",
        lane: "security",
        docs_url: "docs/audit-rubric.md#top-level-risk-mapping",
        owner_hint: "ops",
        evidence_kind: "policy-manifest",
        severity: "high",
        repairable: true,
    },
    RuleSpec {
        id: "HLT-013-RENDERED-UX-GAP",
        name: "Rendered UX proof gap",
        category: "ux-qa",
        tlr: "Verification and rendered UX",
        lane: "web",
        docs_url: "docs/testing.md",
        owner_hint: "tools",
        evidence_kind: "ux-proof",
        severity: "high",
        repairable: true,
    },
    RuleSpec {
        id: "HLT-014-A11Y-GAP",
        name: "Accessibility proof gap",
        category: "ux-qa",
        tlr: "Verification and rendered UX",
        lane: "web",
        docs_url: "docs/agent-native-standard.md",
        owner_hint: "tools",
        evidence_kind: "ux-proof",
        severity: "high",
        repairable: true,
    },
    RuleSpec {
        id: "HLT-015-CONTEXT-SETUP-GAP",
        name: "Context and setup gap",
        category: "context",
        tlr: "Context/setup",
        lane: "fast",
        docs_url: "docs/agent-native-standard.md",
        owner_hint: "agent",
        evidence_kind: "policy-manifest",
        severity: "medium",
        repairable: true,
    },
    RuleSpec {
        id: "HLT-016-SUPPLY-CHAIN-DRIFT",
        name: "Supply-chain drift",
        category: "security",
        tlr: "Security, secrets, agency",
        lane: "security",
        docs_url: "docs/audit-rubric.md#top-level-risk-mapping",
        owner_hint: "ops",
        evidence_kind: "workflow-command",
        severity: "high",
        repairable: true,
    },
    RuleSpec {
        id: "HLT-017-OPAQUE-OBSERVABILITY",
        name: "Opaque observability",
        category: "observability",
        tlr: "Repair",
        lane: "observability",
        docs_url: "agent/JANKURAI_STANDARD.md#repair-receipts",
        owner_hint: "tools",
        evidence_kind: "repository-scan",
        severity: "high",
        repairable: true,
    },
    RuleSpec {
        id: "HLT-018-PERF-CONCURRENCY-DRIFT",
        name: "Performance and concurrency drift",
        category: "proof",
        tlr: "Verification",
        lane: "fast",
        docs_url: "docs/testing.md",
        owner_hint: "tools",
        evidence_kind: "repository-scan",
        severity: "medium",
        repairable: true,
    },
    RuleSpec {
        id: "HLT-019-STREAMING-RUNTIME-DRIFT",
        name: "Streaming runtime drift",
        category: "boundary",
        tlr: "Contracts/data",
        lane: "db",
        docs_url: "docs/streaming.md",
        owner_hint: "tools",
        evidence_kind: "boundary-scan",
        severity: "high",
        repairable: true,
    },
    RuleSpec {
        id: "HLT-020-CI-HARDENING-GAP",
        name: "CI workflow hardening gap",
        category: "security",
        tlr: "Security, secrets, agency",
        lane: "security",
        docs_url: "docs/audit-rubric.md#top-level-risk-mapping",
        owner_hint: "ops",
        evidence_kind: "policy-manifest",
        severity: "high",
        repairable: true,
    },
    RuleSpec {
        id: "HLT-021-DESTRUCTIVE-MIGRATION",
        name: "Destructive SQL migration without safety evidence",
        category: "data",
        tlr: "Contracts/data",
        lane: "db-migration-analyze",
        docs_url: "docs/testing.md",
        owner_hint: "tools",
        evidence_kind: "sql",
        severity: "high",
        repairable: true,
    },
];

pub fn all() -> &'static [RuleSpec] {
    RULES
}

pub fn lookup(rule_id: &str) -> Option<RuleSpec> {
    RULES.iter().copied().find(|rule| rule.id == rule_id)
}

pub fn docs_for_rule_id(rule_id: &str) -> Option<&'static str> {
    lookup(rule_id).map(|rule| rule.docs_url)
}
