use crate::model::*;
use std::collections::HashSet;

pub const WEIGHTS: &[(&str, u32)] = &[
    ("Ownership and navigation surface", 14),
    ("Contract and boundary integrity", 14),
    ("Proof lanes and test routing", 14),
    ("Security and supply-chain posture", 14),
    ("Code shape and semantic surface", 12),
    ("Data truth and workflow safety", 8),
    ("Observability and repair evidence", 8),
    ("Context economy and agent instructions", 8),
    ("Python containment and polyglot hygiene", 4),
    ("Build speed signals", 4),
];

pub const ALLOWED_PYTHON_ROOTS: &[&str] = &[
    ".github",
    "benchmarks",
    "docs",
    "examples",
    "paper",
    "python/ai-service",
    "reference",
    "scripts",
    "tests",
    "tools",
];

pub const OWNER_MAP_PREFIXES: &[(&str, &str)] = &[
    ("AGENTS.md", "agent"),
    ("README.md", "workspace"),
    ("Justfile", "workspace"),
    ("package.json", "workspace"),
    ("package-lock.json", "workspace"),
    (".github/", "ops"),
    ("agent/", "agent"),
    ("assets/", "paper"),
    ("docs/", "standard"),
    ("crates/", "tools"),
    ("packages/ux-qa/", "tools"),
    ("paper/", "paper"),
    ("reference/", "read-only"),
    ("tips/", "paper"),
    ("tools/", "tools"),
];

#[derive(Clone)]
pub struct AuditContext {
    pub root: std::path::PathBuf,
    pub all_files: Vec<FileInfo>,
    pub scope_files: Vec<FileInfo>,
    pub scope_paths: Vec<String>,
    pub self_audit: bool,
}

pub fn weight_for(name: &str) -> u32 {
    WEIGHTS
        .iter()
        .find(|(n, _)| *n == name)
        .map(|(_, w)| *w)
        .unwrap_or(0)
}

pub fn make_dim(
    name: &str,
    score: i32,
    evidence: Vec<String>,
    notes: Vec<String>,
) -> DimensionResult {
    let w = weight_for(name);
    DimensionResult {
        name: name.into(),
        weight: w,
        score: score.clamp(0, 100),
        weighted_points: (w as f64) * (score.clamp(0, 100) as f64) / 100.0,
        evidence,
        notes,
    }
}

// --- Surface predicates ---

pub fn has_root_agents(ctx: &AuditContext) -> bool {
    ctx.all_files.iter().any(|f| f.rel_path == "AGENTS.md")
}

pub fn has_one_command(ctx: &AuditContext) -> bool {
    let t = command_surface_text(ctx);
    t.contains("\ncheck:")
        || t.contains("\nfast:")
        || t.contains("\nsetup:")
        || t.contains("\nverify:")
        || t.contains("\ninstall:")
        || t.contains("\nbootstrap:")
}

pub fn has_fast_lane(ctx: &AuditContext) -> bool {
    real_command_surface_contains(
        ctx,
        &[
            "cargo check",
            "cargo nextest",
            "vitest",
            "pytest",
            "go test",
            "humanlint",
        ],
    )
}

pub fn has_security_lane(ctx: &AuditContext) -> bool {
    let t = security_lane_text(ctx);
    [
        "tools/security-lane.sh",
        "gitleaks detect",
        "dependency-review-action",
        "syft ",
        "grype ",
        "zizmor ",
        "cargo deny",
        "cargo audit",
        "npm audit",
    ]
    .iter()
    .any(|needle| t.contains(needle))
}

pub fn has_humanlint_audit_ci_lane(ctx: &AuditContext) -> bool {
    real_command_surface_contains(ctx, &["cargo run -p humanlint", "repo-score"])
}

pub fn is_high_risk_repo(ctx: &AuditContext) -> bool {
    product_code_files(ctx).iter().any(|f| f.is_code)
        || ctx.all_files.iter().any(|f| {
            ["package.json", "pyproject.toml", "Cargo.toml", "go.mod"].contains(&f.name.as_str())
        })
}

pub fn has_contract_surface(ctx: &AuditContext) -> bool {
    has_prefix(ctx, "contracts")
        || ctx.all_files.iter().any(|f| {
            f.text.contains("openapi") || f.text.contains("protobuf") || f.suffix == ".proto"
        })
}

pub fn has_polyglot_boundary(ctx: &AuditContext) -> bool {
    has_prefix(ctx, "apps/web")
        || has_prefix(ctx, "apps/api")
        || has_prefix(ctx, "crates/domain")
        || has_prefix(ctx, "crates/application")
        || has_prefix(ctx, "crates/adapters")
}

pub fn has_generated_contracts(ctx: &AuditContext) -> bool {
    ctx.all_files.iter().any(|f| {
        f.rel_path == "agent/generated-zones.toml"
            || f.rel_path.contains("/generated/")
            || f.text.contains("Generated by:")
    })
}

pub fn has_api_drift_checks(ctx: &AuditContext) -> bool {
    let t = command_surface_text(ctx);
    t.contains("cargo public-api")
        || t.contains("cargo semver")
        || t.contains("api-extractor")
        || t.contains("tsd")
        || t.contains("openapi-diff")
}

pub fn has_secret_or_dependency_scans(ctx: &AuditContext) -> bool {
    let t = security_lane_text(ctx);
    [
        "tools/security-lane.sh",
        "gitleaks",
        "dependency-review",
        "syft",
        "grype",
        "cargo audit",
        "npm audit",
    ]
    .iter()
    .any(|needle| t.contains(needle))
}

pub fn has_playwright_e2e(ctx: &AuditContext) -> bool {
    if !has_web_surface(ctx) {
        return true;
    }
    real_command_surface_contains(ctx, &["playwright"])
        || ctx
            .all_files
            .iter()
            .any(|f| f.rel_path.contains("e2e") || f.text.contains("@playwright/test"))
}

pub fn has_rust_surface(ctx: &AuditContext) -> bool {
    ctx.all_files
        .iter()
        .any(|f| f.suffix == ".rs" && is_runtime_stack_surface(f, ctx.self_audit))
}

pub fn has_rust_property_tests(ctx: &AuditContext) -> bool {
    !has_rust_surface(ctx)
        || ctx.all_files.iter().any(|f| {
            f.text.contains("proptest")
                || f.text.contains("quickcheck")
                || f.text.contains("rstest")
        })
}

pub fn has_rust_integration_tests(ctx: &AuditContext) -> bool {
    !has_rust_surface(ctx)
        || ctx.all_files.iter().any(|f| {
            f.suffix == ".rs"
                && (f.rel_path.contains("/tests/")
                    || f.rel_path.starts_with("tests/")
                    || f.text.contains("#[test]")
                    || f.text.contains("#[tokio::test]"))
        })
}

pub fn has_web_surface(ctx: &AuditContext) -> bool {
    ctx.all_files.iter().any(|f| {
        !f.rel_path.starts_with("docs/")
            && !f.rel_path.starts_with("paper/")
            && !f.rel_path.starts_with("reference/")
            && !f.rel_path.starts_with("tips/")
            && !f.rel_path.starts_with("agent/")
            && (f.rel_path.starts_with("apps/web")
                || f.rel_path.starts_with("frontend")
                || f.rel_path.starts_with("ui")
                || f.rel_path.starts_with("packages/web")
                || f.rel_path.starts_with("packages/ui")
                || f.text.contains("react")
                || f.text.contains("vite")
                || f.text.contains("storybook"))
    })
}

pub fn has_agent_friendly_exceptions(ctx: &AuditContext) -> bool {
    product_files(ctx).iter().any(|f| {
        let lower = f.text.to_ascii_lowercase();
        let shape = lower.contains("thiserror")
            || lower.contains("enum error")
            || lower.contains("extends error")
            || lower.contains("exception");
        let markers = [
            "purpose",
            "reason",
            "common fixes",
            "docs_url",
            "repair_hint",
        ]
        .iter()
        .filter(|m| lower.contains(**m))
        .count();
        shape && markers >= 3
    }) || has_agent_friendly_exception_docs(&observability_docs_text(ctx))
}

pub fn has_agent_friendly_exception_docs(text: &str) -> bool {
    text.contains("purpose")
        && text.contains("reason")
        && text.contains("common fixes")
        && (text.contains("docs_url") || text.contains("repair_hint"))
}

pub fn has_prefix(ctx: &AuditContext, prefix: &str) -> bool {
    ctx.all_files.iter().any(|f| {
        f.rel_path == prefix
            || f.rel_path
                .starts_with(&format!("{}/", prefix.trim_end_matches('/')))
    })
}

// --- Text aggregation ---

pub fn command_surface_text(ctx: &AuditContext) -> String {
    super::evidence::operational_command_text(&ctx.all_files)
}

pub fn real_command_surface_contains(ctx: &AuditContext, needles: &[&str]) -> bool {
    super::evidence::operational_command_lines(&ctx.all_files)
        .into_iter()
        .any(|line| {
            needles
                .iter()
                .any(|needle| line.contains(&needle.to_ascii_lowercase()))
        })
}

pub fn security_lane_text(ctx: &AuditContext) -> String {
    let mut text = command_surface_text(ctx);
    if let Some(script) = ctx
        .all_files
        .iter()
        .find(|f| f.rel_path == "tools/security-lane.sh")
    {
        text.push('\n');
        text.push_str(&script.text.to_ascii_lowercase());
    }
    text
}

pub fn observability_docs_text(ctx: &AuditContext) -> String {
    let mut text = String::new();
    for path in [
        "docs/testing.md",
        "docs/release-plan.md",
        "docs/agent-native-standard.md",
        "agent/HUMANLINT_STANDARD.md",
    ] {
        if let Some(file) = ctx.all_files.iter().find(|f| f.rel_path == path) {
            text.push('\n');
            text.push_str(&file.text.to_ascii_lowercase());
        }
    }
    text
}

pub fn db_policy_text(ctx: &AuditContext) -> String {
    let mut text = String::new();
    for path in [
        "db/README.md",
        "db/migrations/README.md",
        "db/constraints/README.md",
    ] {
        if let Some(file) = ctx.all_files.iter().find(|f| f.rel_path == path) {
            text.push('\n');
            text.push_str(&file.text.to_ascii_lowercase());
        }
    }
    text
}

// --- File classification ---

pub fn is_runtime_stack_surface(file: &FileInfo, self_audit: bool) -> bool {
    !file.is_generated
        && !matches!(
            file.name.as_str(),
            "AGENTS.md"
                | "CLAUDE.md"
                | "Cargo.lock"
                | "Cargo.toml"
                | "GEMINI.md"
                | ".gitignore"
                | ".latexmkrc"
                | "Justfile"
                | "Makefile"
                | "README.md"
                | "VERSION"
                | "makefile"
                | "justfile"
                | "package-lock.json"
                | "package.json"
        )
        && !file.rel_path.starts_with("agent/")
        && !file.rel_path.starts_with(".claude/")
        && !file.rel_path.starts_with(".cursor/")
        && !file.rel_path.starts_with(".agents/")
        && !file.rel_path.starts_with("assets/")
        && (self_audit || !file.rel_path.starts_with("crates/humanlint/"))
        && !file.rel_path.starts_with("schemas/")
        && !["contracts/", "db/", "migrations/", "ops/", "/.github/"]
            .iter()
            .any(|p| file.rel_path.starts_with(p))
        && !file.rel_path.starts_with("docs/")
        && !file.rel_path.starts_with(".github/")
        && !file.rel_path.starts_with("paper/")
        && !file.rel_path.starts_with("reference/")
        && !file.rel_path.starts_with("examples/")
        && (self_audit || !file.rel_path.starts_with("packages/ux-qa/"))
        && !file.rel_path.starts_with("scripts/")
        && !file.rel_path.starts_with("tests/")
        && !file.rel_path.starts_with("tips/")
        && !file.rel_path.starts_with("tools/")
}

pub fn product_files(ctx: &AuditContext) -> Vec<FileInfo> {
    ctx.all_files
        .iter()
        .filter(|f| is_runtime_stack_surface(f, ctx.self_audit))
        .cloned()
        .collect()
}

pub fn product_code_files(ctx: &AuditContext) -> Vec<FileInfo> {
    product_files(ctx)
        .into_iter()
        .filter(|f| f.is_code)
        .collect()
}

pub fn python_ratio(ctx: &AuditContext) -> f64 {
    let files = product_files(ctx);
    let total: usize = files.iter().map(|f| f.line_count).sum();
    let py: usize = files
        .iter()
        .filter(|f| f.suffix == ".py")
        .map(|f| f.line_count)
        .sum();
    if total == 0 {
        0.0
    } else {
        py as f64 / total as f64
    }
}

pub fn is_allowed_python_path(path: &str) -> bool {
    ALLOWED_PYTHON_ROOTS
        .iter()
        .any(|p| path == *p || path.starts_with(&format!("{}/", p.trim_end_matches('/'))))
}

pub fn bad_python_paths(ctx: &AuditContext) -> bool {
    ctx.all_files
        .iter()
        .any(|f| f.suffix == ".py" && !is_allowed_python_path(&f.rel_path))
}

pub fn max_loc(files: &[FileInfo]) -> Option<usize> {
    files.iter().map(|f| f.line_count).max()
}

pub fn largest_file(files: &[FileInfo]) -> Option<FileInfo> {
    files.iter().max_by_key(|f| f.line_count).cloned()
}

pub fn root_readme_routes(ctx: &AuditContext) -> bool {
    ctx.all_files
        .iter()
        .find(|f| f.rel_path == "README.md")
        .map(|f| {
            let lower = f.text.to_ascii_lowercase();
            [
                "build",
                "flow",
                "layout",
                "map",
                "paper/",
                "reference/",
                "tools/",
                "validate",
                "workspace",
            ]
            .iter()
            .any(|m| lower.contains(m))
        })
        .unwrap_or(false)
}

pub fn missing_core_docs(ctx: &AuditContext) -> Vec<String> {
    let present: HashSet<_> = ctx.all_files.iter().map(|f| f.rel_path.as_str()).collect();
    let mut missing = vec![];
    for need in ["AGENTS.md", "README.md"] {
        if !present.contains(need) {
            missing.push(need.into());
        }
    }
    if !(present.contains("docs/architecture.md") || present.contains("docs/boundaries.md")) {
        missing.push("docs/architecture.md or docs/boundaries.md".into());
    }
    if (has_web_surface(ctx) || has_rust_surface(ctx)) && !present.contains("docs/testing.md") {
        missing.push("docs/testing.md".into());
    }
    missing
}

pub fn boundary_manifest(
    ctx: &AuditContext,
) -> Option<crate::boundaries::manifest::BoundaryManifest> {
    crate::boundaries::manifest::load(&ctx.root.join("agent/boundaries.toml")).ok()
}

pub fn path_matches_prefix(path: &str, prefix: &str) -> bool {
    let prefix = prefix.trim_end_matches('/');
    path == prefix || path.starts_with(&format!("{prefix}/"))
}

pub fn paths_with(ctx: &AuditContext, path_markers: &[&str], markers: &[&str]) -> Vec<String> {
    let mut out = vec![];
    for f in &ctx.all_files {
        if f.rel_path.starts_with("docs/")
            || f.rel_path.starts_with("paper/")
            || f.rel_path.starts_with("reference/")
            || f.rel_path.starts_with("tips/")
        {
            continue;
        }
        let rel = f.rel_path.to_ascii_lowercase();
        let text = f.text.to_ascii_lowercase();
        let path_hit = path_markers
            .iter()
            .any(|m| rel.contains(&m.to_ascii_lowercase()));
        let text_hit = markers
            .iter()
            .any(|m| text.contains(&m.to_ascii_lowercase()));
        if path_hit || text_hit {
            out.push(f.rel_path.clone());
        }
        if out.len() >= 5 {
            break;
        }
    }
    out
}

// --- Repair exception ---

#[derive(Debug, Clone)]
pub struct AuditRepairException {
    pub purpose: &'static str,
    pub reason: &'static str,
    pub common_fixes: &'static [&'static str],
    pub docs_url: &'static str,
    pub repair_hint: &'static str,
}

pub fn audit_repair_exception() -> AuditRepairException {
    AuditRepairException {
        purpose: "route repair work to the next agent",
        reason: "opaque failures slow local debugging and reruns",
        common_fixes: &[
            "add a typed repair hint",
            "name the common fixes",
            "point at the local docs URL",
        ],
        docs_url: "docs/testing.md",
        repair_hint: "define a typed exception surface with purpose, reason, common fixes, docs_url, and repair_hint so the next rerun is local",
    }
}

// --- Non-optimal language detection ---

pub fn non_optimal_language_hits(ctx: &AuditContext) -> Vec<FileInfo> {
    product_code_files(ctx)
        .into_iter()
        .filter(|f| {
            [
                ".c", ".cc", ".cpp", ".cs", ".dart", ".ex", ".exs", ".go", ".h", ".hh", ".hpp",
                ".java", ".js", ".jsx", ".kt", ".kts", ".lua", ".m", ".mm", ".php", ".rb",
                ".scala", ".swift",
            ]
            .contains(&f.suffix.as_str())
                || (f.suffix == ".py" && !f.rel_path.starts_with("python/ai-service/"))
        })
        .collect()
}

// --- Handwritten API detection ---

pub fn handwritten_api_hits(ctx: &AuditContext) -> bool {
    product_code_files(ctx).iter().any(|f| {
        (f.rel_path.starts_with("apps/web/")
            || f.rel_path.starts_with("frontend/")
            || f.rel_path.starts_with("ui/")
            || f.rel_path.starts_with("src/"))
            && (f.text.contains("fetch(")
                || f.text.contains("axios.")
                || f.text.contains("XMLHttpRequest")
                || f.text.contains("Request") && f.text.contains("Response"))
    })
}

// --- Domain IO detection ---

pub fn domain_io_hits(ctx: &AuditContext) -> Vec<String> {
    product_code_files(ctx)
        .into_iter()
        .filter(|f| f.rel_path.contains("/core/") || f.rel_path.contains("/domain/"))
        .filter(|f| {
            [
                "fetch(",
                "open(",
                "read(",
                "requests.",
                "socket",
                "std::fs",
                "subprocess",
                "write(",
                "println!",
            ]
            .iter()
            .any(|m| f.text.contains(m))
        })
        .map(|f| f.rel_path)
        .collect()
}

pub fn weak_name_hits(_ctx: &AuditContext) -> Vec<String> {
    vec![]
}

pub fn missing_owner_paths(ctx: &AuditContext) -> Vec<String> {
    let Some(map) = load_owner_map(ctx) else {
        return vec![];
    };
    auditable_manifest_paths(ctx)
        .into_iter()
        .filter(|path| !matches_prefix(path, map.owners.keys()))
        .collect()
}

pub fn missing_test_paths(ctx: &AuditContext) -> Vec<String> {
    let Some(map) = load_test_map(ctx) else {
        return vec![];
    };
    auditable_manifest_paths(ctx)
        .into_iter()
        .filter(|path| !matches_prefix(path, map.tests.keys()))
        .filter(|path| !path.starts_with("reference/"))
        .collect()
}

fn load_owner_map(ctx: &AuditContext) -> Option<crate::commands::context_data::OwnerMapFile> {
    std::fs::read_to_string(ctx.root.join("agent/owner-map.json"))
        .ok()
        .and_then(|text| serde_json::from_str(&text).ok())
}

fn load_test_map(ctx: &AuditContext) -> Option<crate::commands::context_data::TestMapFile> {
    std::fs::read_to_string(ctx.root.join("agent/test-map.json"))
        .ok()
        .and_then(|text| serde_json::from_str(&text).ok())
}

fn auditable_manifest_paths(ctx: &AuditContext) -> Vec<String> {
    ctx.scope_files
        .iter()
        .filter(|file| {
            !file.rel_path.starts_with(".git/")
                && !file.rel_path.starts_with("target/")
                && !file.rel_path.starts_with("node_modules/")
                && !file.rel_path.starts_with("paper/humanlint.")
                && !file.rel_path.starts_with("reference/")
        })
        .map(|file| file.rel_path.clone())
        .collect()
}

fn matches_prefix<'a>(path: &str, prefixes: impl Iterator<Item = &'a String>) -> bool {
    prefixes.into_iter().any(|prefix| {
        path == prefix
            || path.starts_with(prefix)
            || path.starts_with(&format!("{}/", prefix.trim_end_matches('/')))
    })
}
